version: "3.5"
services:
  mysql:
    container_name: taiwanlottery
    image: mysql:5.7
    ports:
      - "3311:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --slow-query-log=ON --log-output=TABLE --long-query-time=1 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taiwanlottery
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
